### ISSUE TITLE
Suggestion : Improve mod configurability.

### ISSUE THREAD

**Issue by zothboy** [Akinesis/better-enchanting#14]
The mod already has a config file, but what we can't do much.

I think that let the player choose the amount of items would be a good adition to the mod config.

**Comment by Akinesis** [comment]
Yup, it's on mu todo -list for thie mod.
Eventualy, i'd like to profide full customization for : Recipes, loot chances, trade offers and enchanting ingredients (already there).

This might not be my highest priority but it's a "planed" feature.

**Comment by Akinesis** [comment]
1.0 version of the mod , th "Configuration Update" is out.
You can diasble from the enchanting table any enchantment you whant via a new config file.
Most value used on the calculation of Xp and Itmes cost are also now configurable.
Enjoy :)
