### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Aarongrey13** [Akinesis/better-enchanting#16]
could you perhaps make a mod that just has the iron and diamond upgrade templates? i would love to be able to have specifically that feature as a part of my modpack

**Comment by Akinesis** [comment]
I'm working on another mod for my private server that add a lot a random things that i whant for me and my friends.
I could rethink it to make each functionality configurable and add the Upgrade Tempalte into this instead.
I'll thin about it.

**Comment by Aarongrey13** [comment]
that would be lovely if you did!

**Comment by johalun** [comment]
Please use more meaningful title. For example
`Suggestion: iron and diamond upgrade templates as separate mod`

This way everyone can see what the suggestion is without having to click on the issue and read through the description.

**Comment by Akinesis** [comment]
Hello, the other mod is up :
https://modrinth.com/mod/the-fox-den-collection
As i said, it's a collections of random features that i've developed for my personal enjoyment. So don't expect much of it.
I'v added the upgrade template to this mod, and ther is a config file to disable unwanted features.
If you have both this mod and Better Enchanting, the upgrade template will be present only on the better enchanting mod.
Have fun :)
