### ISSUE TITLE
Compatibility with Villager Trade Rebalance experiment

### ISSUE THREAD

**Issue by VINEGARSYNDROME** [Akinesis/better-enchanting#18]
would it be possible to make this mod compatible with the [villager trade rebalance experiment](https://minecraft.wiki/w/Villager_Trade_Rebalance)? i think the two would work well together. would it also be possible to readd enchanted books in that version? thanks!

**Comment by Akinesis** [comment]
Yeah, this should be a qucik fix that is on mu to-do list for a while.
It should be up soon.

**Comment by Akinesis** [comment]
I've added compatibility with the 0.7.4 version.
I've not yet create specific item repartition depanding on biomes, but i'll add them soon.
