### ISSUE TITLE
The Essence not override the enchantment book loot

### ISSUE THREAD

**Issue by Sushikee** [Akinesis/better-enchanting#2]
I use the Better Enchanting mod. I generate new world and I can't find the essence anyway in any sturcture.

**Comment by Akinesis** [comment]
Essences have the same loot chance than enchanted books. So it's pretty rare and can only be found if chest on some specific location (like stronghold, ancient city, or jungle temple to name a few).
I've re-tested the loot mechanic and it's working.
I'm currently working on adding ways to craft every essence in survival, it was never the goal the rely solly on looting or trading, on the contrary.

**Comment by Sushikee** [comment]
So, I went to the ancient city and still have enchantment books in the chest there
