### ISSUE TITLE
Spell Engine Compat

### ISSUE THREAD

**Issue by Cheesy-Brik** [Akinesis/better-enchanting#20]
Spell engine is a pretty common mod used especially in the rpg series mods. I think because this mod fits so well with those vibes it would be best to add built-in compatibility to those mods.

**Comment by Akinesis** [comment]
I will look into it.
If it's not too complicated, it might be in the next patch for the mod.

**Comment by Akinesis** [comment]
Full support for all Spell Engine mods (including combat roll) is done.
The chages are in the 0.8.0 and up of the mod :)
