### ISSUE TITLE
Diversity Compatibility

### ISSUE THREAD

**Issue by FaeWulf** [Akinesis/better-enchanting#22]
Hello! 
I am the creator of Diversity (https://modrinth.com/mod/faewufs-diversity) And Better bundle (https://modrinth.com/mod/diversity-better-bundle)
My 2 mods containing some custom enchantment for bundle (capacity, refill) and armor (Backup enchantments) But it seems like the mod not supports it by default.

So I want to ask if there is a way to add compact myself?

Thank you very much!

**Comment by Akinesis** [comment]
Yeah, enchantability of items not tipicaly enchantable is not automatic in most case.
I'll work on a comp patch rignt now, it should take too long.
(And might as well think of a way to add a more robust solution)

**Comment by Akinesis** [comment]
I've add a way for other mod to add custom entry to the enchantments/Ingredients map.
See the readme on git for more information on that (don't esitate to reach out to me if it's not clear or if it doesn't work).

I've also added built-in compatibility for your bundle enchantment, as i suspect that other mods might add bundle enchant, so creating custom essences for them seems apropriate.
