### ISSUE TITLE
[Suggestion] Resource pack that change book icons compatibility

### ISSUE THREAD

**Issue by heide-oficial** [Akinesis/better-enchanting#23]
I would really love if your mod had compatibility with mods that add better book models (like [this one](https://modrinth.com/resourcepack/bibliophilia)), so instead of the same boring books on the GUI, we actually have some cool books to look at. Example:

![custom_enchanted_books_example](https://github.com/user-attachments/assets/9a0e035b-55dd-4682-ab07-081840aa3e3c)

**Comment by Akinesis** [comment]
Custom book texture for each encahnts is on my to-do list for this mod.
But on a realy low priority.
I might look for a compat with mod handeling custom item model (CIT) to delegate the actuale drawing to other people with more talent than me ;)

**Comment by Akinesis** [comment]
It was easier tahn expected : 
![Image](https://github.com/user-attachments/assets/9d45e0ed-0e03-41ab-a25a-837d0fa7fd06)
The mod now draw directly the enchanted book on the UI so if you have client-side mod that change Enchanted Books texture, it should render them in the enchanting table UI.
The feature is added in the 0.7.6 version of Better Encahnting.

**Comment by heide-oficial** [comment]
Amazing!!! Thanks for the awesome addition!!
