### ISSUE TITLE
[Mod Support] Combat Roll

### ISSUE THREAD

**Issue by heide-oficial** [Akinesis/better-enchanting#24]
I can't play Minecraft without Better Combat + Combat Roll mods, and [Combat Roll](https://modrinth.com/mod/combat-roll) actually adds 3 new enchantments, so I would love for your mod to have compatibility with these enchantments as well!

**Comment by heide-oficial** [comment]
The mod already has Combat Roll compatibility and I didn't know.

**Comment by heide-oficial** [comment]
Actually I'm on drugs. It doesn't have Combat Roll compatibility, as we need a barrier to get the enchantments LOL

**Comment by Akinesis** [comment]
Combat roll compat will be handeled in the next major version of this mod, allong Spell Engine and all related mod compat.

In the meantime, you can manualy add a "soft-compatibility" by editing the config file (on the server) and adding entry for the concerned enchantments.
See the wiki : [Modifing ingredients list and adding support to moded enchantments.](https://github.com/Akinesis/better-enchanting/wiki/Modifing-ingredients-list-and-adding-support-to-moded-enchantments.)

**Comment by Akinesis** [comment]
Full support for all Spell Engine mods is done.
The chages are in the 0.8.0 and up of the mod :)
