### ISSUE TITLE
[Suggestion] Enchantment descriptions when mouse over

### ISSUE THREAD

**Issue by heide-oficial** [Akinesis/better-enchanting#25]
It would be really cool and useful if we could see what each exactly each enchantment does by hovering the mouse over a upgrade. Example:
![enchantment_description_example](https://github.com/user-attachments/assets/eaad02e2-23c6-435c-ac47-8c6467592493)

**Comment by Akinesis** [comment]
Adding such features are out of the scope of this mod. It would require a lot of additional work on a lot of things unrelated to the core concept of Better Enchanting.
I might add compatibility with mods that do exactly this, like [Enchantment Descriptions](https://modrinth.com/mod/enchantment-descriptions), but it's not on my to-do list right now.
