### ISSUE TITLE
Essence still not spawning in loot chest

### ISSUE THREAD

**Issue by Sushikee** [Akinesis/better-enchanting#3]
Hello! Thanks for the new update that made essence craftable although some recipe is a bit overkill (hope you planned to balance it out).
I would like to inform a bug which I can still find enchantment books in chest despite it dont have any use no more. I also still couldnt find essence anywhere in chest loot

![2024-07-06_12 51 10](https://github.com/Akinesis/better-enchanting/assets/174824674/73fa87f3-aa39-45e8-819f-aa5c08948a23)
![2024-07-06_12 51 42](https://github.com/Akinesis/better-enchanting/assets/174824674/db002694-d85c-4c67-b7da-239f6df3e824)

**Comment by Akinesis** [comment]
Are you using any mod along with this ? I see enchanted books on the chest you are looking at, it should not be possible as the mod rewrite the loot table to get rid of them.
I'v made a few test run opening chest in Ancient cities, Bastion Remnant, Stronghold and Dungeon and was always able to find essence. **At a very low rate** mind you. I might tweak the loot chance a litle but as of now, the mod use the same rarirty as enchanted books.

As for the overkill of some recipe ... Yeah, some might need a litle blance. But all recipe should need mid/end game ingredients. The goal to to force you to progress along the game.

**Comment by Akinesis** [comment]
Version 0.5.0 should resolve all compatibility issiues with other mods.
