### ISSUE TITLE
Enchantments don't show up despite being in the config, even by default

### ISSUE THREAD

**Issue by SemiDemiGoddess** [Akinesis/better-enchanting#30]
Some enchantments don't show up on the table for their corresponding item. An example is like below;
  "enchantplus:pickaxe/spawner_touch": [
    "betterenchanting:essence_of_silk_touch"
  ],
Spawner Touch is in by default when playing with Neo Enchanting but does not show up when trying to enchant a pickaxe. This does not apply to all the enchantments as for instance, Fury from the same mod still shows up for all armor pieces, appearing as such in the config;
  "enchantplus:armor/fury": [
    "minecraft:sugar",
    "minecraft:iron_sword",
    "minecraft:diamond_axe",
    "betterenchanting:essence_of_combat"
],
There is no indication of why some work and others don't

**Comment by Akinesis** [comment]
Hello, the enchantment available in the enchanting table are the ones present in the tags "in_enchanting_table" or "treasure" (and that are not a curse).
So anny enchant added by other mods that are not in these tags are not visible in the enchanting table.
By default, the enchantment "spawner_touch" of the mod Neo Enchant+" is only present in Ygrasil companion mod. I've added the configuration for it if you wich to modifie the Neo Enchant+ datapack to provide this enchant (or any other in the same situation) with tags like  "treasure" or even "in_enchanting_table".
Hope that this help clarify the sitatuation ;)

**Comment by SemiDemiGoddess** [comment]
Oh! Gotcha! Thank you so much
