### ISSUE TITLE
Enchancement Mod Compatibility

### ISSUE THREAD

**Issue by BM123789** [Akinesis/better-enchanting#33]
https://modrinth.com/mod/enchancement
I think your mod presents a great way of obtaining enchantments. The mod I put adds some very unique enchantments that can really change one's playstyle, and I thought it would be cool if you could add mod compatibility for this mod.

**Comment by Akinesis** [comment]
My mod and this mod add very similar mechanics and i'm not sure a compat is feasible att all.
I agree thought that some of the enchants added by this mod are realy cool, but 33 is a loot of new enchantments for adding custom sprites, recipes and ingredients --'
I might look into it, but not right now.

**Comment by BM123789** [comment]
That's fair, thanks for putting it into consideration. Also, out of curiosity, would my world break if I added your mod to it after the world already existing?

**Comment by Akinesis** [comment]
Nop !
Nothing should break. The only "unwanted consequence" is that any enchanted books already generated will stay as is.
And as for now, enchented books are rendered useless with my mod. But other tahtn that, addin or removing my mod should not breaking thigs.
