### ISSUE TITLE
Mending not showing

### ISSUE THREAD

**Issue by JoBuddy** [Akinesis/better-enchanting#34]
When I place any sword of armor or tool into the enchanter mending is not showing up.  Even when I place the essence into the enchanter.

**Comment by Akinesis** [comment]
Do you have enought bookshelves aroud the enchanting table ?
The mod keep the vanilia behaviour of Minecraft behaviour of enchanting table. The more you have bookshelves around the table, the better the enchantments proposed are.

Mending beeing a Treasue enchantment, you have to place more bookshelves around the enchanting table. The maximum is 15, just like vanilia Minecraft.

If it's the case but yu still don't see Mending, keep me in touch.

**Comment by JoBuddy** [comment]
Yeah that's what I thought I placed as many bookshelves as I could fully enclosing the enchanter. I can only see normally visible enchantments so it's not only mending but also, soul speed and so on.

**Comment by JoBuddy** [comment]
I actually fixed it. It was another (library) mod interfering with the enchanter. Just rewrote some code of this mod now so it does not effect the enchanter anymore. Sorry to have bortherd you with that.

**Comment by Akinesis** [comment]
Haha no problems !
 Glad you manage to resolve the situation :)
