### ISSUE TITLE
mending accessibility

### ISSUE THREAD

**Issue by agrovator** [Akinesis/better-enchanting#35]
I love this mod I'm just only concerned about how theoretically easy it is to get mending very early on since it seems to use materials that are all obtainable in the overworld. Personally I'd like to see it as more of an endgame enchantment (especially with the buffs to repairing) needing some materials from the nether or even end but I understand this might just be my opinion.
If you could let me know if this would be considered that would be great. Thanks

**Comment by Akinesis** [comment]
The idea behing mending is that's it "lock" behinde the asuisition of XP Bottle. And the fact that you need to have gone to the Nether to craft Magic Shards.
I agree that Mending should be a bit difficult to craft (hence Mending Essence beehing the only essence with another essence as ingredient), but it's a way too popular enchant for me to make it too diffucult.
Most player consider their game to start when the get Mending Tools and armor, and i don't fill confortable locking it too far in the progression of the game.

You could technicaly modifie the recipe for Mending Essence with a simple datapack, i you personaly whant to make it arder to acquire, but it's unlikly that i would drasticly change this particular recipe.
If you have a recipe in mind that could work, feel free to share with me here. Perhaps one with Two Essence Of Experience ?

**Comment by agrovator** [comment]
I guess I overlooked the magic shards being nether-locked as I thought they were sold by villagers but I might have been mistaken. In that case I'll have to play around with the mod more to really see how long it takes to farm up enough for a full mending set. I just liked the changes to repairing and thought it would be nice to see that feature more utilized and make mending feel less necessary than it is currently while still being a great reward.

Also I would love to see a discord server for this mod as it's my favorite enchanting mod by far but either way great job and I'll keep testing how it feels balance-wise.

**Comment by Akinesis** [comment]
I agree that Mending is not that hard to get, but you have to factor in the XP cost.
As it is a Treasure enchant, the cost of it is double. Nothing too problematic is you have an XP famr, but then you are not realy "early game" anymore.

As for the Discord, i'm not realy active with the app, so i'm reluctant to create a server that i would then have to moderate etc ...
But i might look into it some day.
