### ISSUE TITLE
Dungeons and Taverns compat

### ISSUE THREAD

**Issue by agrovator** [Akinesis/better-enchanting#36]
I've noticed that regular chests in the new structures spawn essences correctly but the new trial spawners and vaults in dungeons and taverns still give enchanted books. Just making this post to whether you're aware of this or already have another workaround that I'm missing.
Edit: from what i can see it seems like the current integration is just making all the enchantments craftable, if thats the case is there plans to eventually remove the recipes and add the essences to the loot tables for the structures they are intended to be found in?

**Comment by Akinesis** [comment]
Hello, yes the compat for now is just loading adequate recipe for them to be usable in survival.
As for generation, the system should detect anny enchants from DnT and replace any enchanted books with appropriates ingredients of Essences.
Trial chambers and vaults are an oversight of mine, i'll correct that as soon as i can.
Thank you for the report.

**Comment by agrovator** [comment]
Sounds good, in the long term it would be nice to see the enchantments implemented as intended with dungeons and taverns being obtainable only through the specific structures, probably by having the loot tables for the enchanted books be replaced directly with the associated essence, but I can see the complications applying that to this system mainly with multi level enchantments. One solution could be to make each level of the enchantment require the essence making you require multiple to get the highest level, but that aspect could also be easily tweaked with the config file.

**Comment by Akinesis** [comment]
yeah, it all depends on how loot is generated with various mods (and vanillia features).

As for an enchant for each level of enchantments, it could be the same as for Soul Speed, with as an enchant for each level and that don't have crafting recipe. But that would mean come with a lot of new sprites, and potential crafting recipe ...

**Comment by Akinesis** [comment]
Trial chamber loot is fixed with 1.1.2 version of the mod.
The next update will offer more option to work with enchanted books and various config options around it.
