### ISSUE TITLE
Config file resetting

### ISSUE THREAD

**Issue by agrovator** [Akinesis/better-enchanting#37]
Any edits made through the betterEnchanting config file are reset to default upon launching the game
![image_2024-12-24_123949045](https://github.com/user-attachments/assets/abf42337-5044-43e7-8ee6-ec5ffa451c70)
![image_2024-12-24_124002132](https://github.com/user-attachments/assets/2df04cda-1888-4ad0-9ef6-8537cf11c57d)

Workaround is to add the enchantments in-game through mod menu which seems to stay after restarting but a small bug nonetheless

**Comment by Akinesis** [comment]
I'll look into it.
Might be due to the order in wich i load the configs ...

**Comment by Akinesis** [comment]
Sorry, didn't check well the first time, i was on my phone.
Entry of disabled enchantment need to be each separtaed by a comma like so : 
```
  "disabledEnchants": [
    "namespace:enchantment",
    "minecraft:mending",
    "nova_structure:gravity"
  ],
```
Only the last entry should be comma-free.
