### ISSUE TITLE
Villagers are now more OP

### ISSUE THREAD

**Issue by supergregg123** [Akinesis/better-enchanting#5]
![image](https://github.com/Akinesis/better-enchanting/assets/77626407/dc06aae2-3a7e-4fd0-a02a-fc243f795be9)
![image](https://github.com/Akinesis/better-enchanting/assets/77626407/bf679cc4-74b9-4929-b161-be2e2a1dfbce)

Librarians are more necessary than before, with most essences being completely ridiculous to craft compared to trading for. They also now offer previously difficult to obtain/farm items like scutes, pistons, heart of the sea, and blue ice.
The mod description said that librarians had been nerfed, so I doubt that this is intended.

I would remove essences from the trade pool, maybe offering them as a master level trade. And having the earlier book trades replaced with infused lapis, dull shards, exp bottles, or something less useful like paper.

Love the mod btw!

**Comment by Akinesis** [comment]
Yup, i agree.
As i removed the books trade to librarians i din't wanted to make them completly useless. But as some recipes are (way too hard) to make, it's in deed making then absoluty necessary.

I'll tweaks recipe a little and maybe move essences trades to Expert / Master tiers.

**Comment by Akinesis** [comment]
I've just push a small update to start balancing things off.
Essences and rare item are ... rare in trade offers and more expensive.
