### ISSUE TITLE
Where to contact you ?

### ISSUE THREAD

**Issue by D3K4P1T4T0R3** [Akinesis/better-enchanting#6]
Sorry to do a useless issue, but i am extremly glad that someone has made this mod (wich the ideas i had since before the videos about it came out) and i really wanna help you more directly in the balacing/designing fase (i'm an inspiring game designer), i can also help with the pixel art, am fine enough at it. So, do you think we could talk on discord or wherever else .... please ? (i will delet the issue after ur answer)

my discord : coolkid_1111

**Comment by Akinesis** [comment]
Hello,
Thank you for your appreciation.
I don't have any other way for contact right now. I'm grateful for your eagerness to help; however, I'm going to decline for now. This project is still very much in construction, and being the only person at the helm is better as of now.
 
I hope you'll keep enjoying this mod in the future.
