### ISSUE TITLE
Missing text when enchanting dull magic shard

### ISSUE THREAD

**Issue by Landrozaum** [Akinesis/better-enchanting#8]
Missing this text when enchanting dull magic shard
![image](https://github.com/user-attachments/assets/bdf803a3-7149-4db0-ad00-f0cbf8e2d9e7)

**Comment by Akinesis** [comment]
Damn ! 
I'm on holliday for two weekends, this will be fixed AT thé end of thé mount.

**Comment by Landrozaum** [comment]
Ok, in your time. When you came back, check pull requests, i made a translation to pt_br.

**Comment by Akinesis** [comment]
Problem is fixed and i've add your translation file. Thank you for your contribution.
